# Chạy dưới quyền root để chắc chắn không bị lỗi phân quyền cổng 53
user=root

# Lắng nghe trên mọi IP của container
listen-address=0.0.0.0
bind-interfaces

# KHÔNG đọc file /etc/resolv.conf của Docker
no-resolv
no-poll

# Khai báo máy chủ phân giải Upstream
server=8.8.8.8
server=1.1.1.1

# Bật log truy vấn trực tiếp vào file cấu hình
log-queries
log-facility=-

# [Records]
address=/.dockitt.local/192.168.101.56
