services:
  bookstack-db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: bookstack-db
    restart: unless-stopped

    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=bookstack_root_secret
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack_secret_password

    volumes:
      - ./data/db-data:/config

    networks:
      dockitt_network:
        ipv4_address: 10.0.0.40

  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    restart: unless-stopped
    depends_on:
      - bookstack-db

    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY=base64:YZ4C6APWGy1e6+Iyq1dgaNDxvz3+ZCmYR4f0fnmkk68=
      - APP_URL=http://docs.dockitt.local
      - DB_HOST=10.0.0.40
      - DB_PORT=3306
      - DB_DATABASE=bookstackapp
      - DB_USERNAME=bookstack
      - DB_PASSWORD=bookstack_secret_password

    volumes:
      - ./data/app-data:/config

    networks:
      dockitt_network:
        ipv4_address: 10.0.0.41

networks:
  dockitt_network:
    external: true
