services:
  gitea-db:
    image: postgres:15-alpine
    container_name: gitea-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea_secret_password
      - POSTGRES_DB=gitea
    volumes:
      - ./data/db-data:/var/lib/postgresql/data
    networks:
      dockitt_network:
        ipv4_address: 10.0.0.20

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    depends_on:
      - gitea-db

    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=10.0.0.20:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea_secret_password
      - GITEA__server__DOMAIN=git.dockitt.local
      - GITEA__server__ROOT_URL=http://git.dockitt.local/
      - GITEA__webhook__ALLOWED_HOST_LIST=*

    dns:
      - 10.0.0.5

    volumes:
      - ./data/gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    networks:
      dockitt_network:
        ipv4_address: 10.0.0.21

networks:
  dockitt_network:
    external: true
